FROM golang:1.24-alpine AS builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY whatsapp-bridge/ .
RUN CGO_ENABLED=1 go build -o whatsapp-bridge main.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/whatsapp-bridge .
VOLUME ["/app/store"]
EXPOSE 8080
CMD ["./whatsapp-bridge"]
